services:
  # Frontend service - React app
  - type: static
    name: forge-frontend
    plan: free
    buildCommand: cd my-voice-assistant && npm install && npm run build
    publishDir: ./my-voice-assistant/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
  
  # Backend service - Python API
  - type: web
    name: forge-api
    plan: free
    env: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: gunicorn backend.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: GEMINI_API_KEY
        sync: false # This will be filled manually in Render dashboard 