services:
  # Combined service for API and frontend
  - type: web
    name: forge-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd my-voice-assistant && npm install && npm run build
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: NODE_VERSION
        value: 18.x
      - key: GEMINI_API_KEY
        sync: false # This will be filled manually in Render dashboard
      - key: FLASK_ENV
        value: production
      - key: SERVE_STATIC
        value: "true"
      - key: LOW_MEMORY_MODE
        value: "true" 