services:
  # Single service combining frontend and backend
  - type: web
    name: forge-app
    env: python
    plan: free
    buildCommand: ./render-build.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: NODE_VERSION
        value: 18
      - key: GEMINI_API_KEY
        sync: false # This will be filled manually in Render dashboard
      - key: FLASK_ENV
        value: production
      - key: ESSENTIAL_VOICES_ONLY
        value: "true"
      - key: PYTHONUNBUFFERED
        value: "1" # Ensure logs are output immediately
    healthCheckPath: /health 