services:
  # Combined service - Python API with Kokoro TTS and serving frontend files
  - type: web
    name: forge-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements-render.txt
      cd my-voice-assistant && npm install && npm run build
    startCommand: ./render-start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: NODE_VERSION
        value: 18
      - key: SERVE_STATIC
        value: true
      - key: GEMINI_API_KEY
        sync: false # This will be filled manually in Render dashboard 